"""VCD waveform API endpoints (/api/vcd/*).

Provides signal listing and Surfer viewer launch for VCD files
generated by HDL simulations (Amaranth, etc.).
"""

from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel

from backend.plugins.python_canvas.vcd_utils import list_vcd_signals, launch_surfer

router = APIRouter(prefix="/api/vcd", tags=["vcd"])

# VCD files are written to the kernel CWD (project root by default)
_PROJECT_ROOT = Path(__file__).parent.parent.parent


def _resolve_vcd_path(file: str) -> Path:
    """Resolve and validate a VCD file path within project root."""
    vcd_path = (_PROJECT_ROOT / file).resolve()
    if not str(vcd_path).startswith(str(_PROJECT_ROOT.resolve())):
        raise HTTPException(403, "Path traversal not allowed")
    if not vcd_path.is_file() or vcd_path.suffix != ".vcd":
        raise HTTPException(404, f"VCD file not found: {file}")
    return vcd_path


@router.get("/signals")
async def get_signals(file: str):
    """List all signals in a VCD file."""
    vcd_path = _resolve_vcd_path(file)
    signals = list_vcd_signals(vcd_path)
    return JSONResponse({"signals": signals, "file": file})


class OpenRequest(BaseModel):
    file: str


@router.post("/open")
async def open_in_surfer(req: OpenRequest):
    """Open a VCD file in Surfer waveform viewer."""
    vcd_path = _resolve_vcd_path(req.file)
    result = launch_surfer(vcd_path)
    status = 200 if result["success"] else 500
    return JSONResponse(result, status_code=status)
