"""VCD file utilities and Surfer waveform viewer launcher.

Parses IEEE 1364-2005 VCD files (as generated by Amaranth) and provides
signal listing. Launches Surfer for interactive waveform viewing.
"""

from __future__ import annotations

import logging
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)

# Surfer executable — search PATH, then common install locations
_SURFER_SEARCH_PATHS = [
    Path.home() / "Downloads" / "surfer_win" / "surfer.exe",
    Path("C:/Program Files/surfer/surfer.exe"),
]


def _find_surfer() -> Path | None:
    """Find the Surfer executable."""
    # Check PATH first
    found = shutil.which("surfer")
    if found:
        return Path(found)
    # Check common locations
    for p in _SURFER_SEARCH_PATHS:
        if p.is_file():
            return p
    return None


def launch_surfer(vcd_path: Path) -> dict:
    """Launch Surfer waveform viewer with the given VCD file.

    Generates a .surf.ron state file so multi-bit signals are displayed
    as analog waveforms (Signed, Step, Viewport) and 1-bit signals as
    standard digital traces.

    Returns:
        {"success": True/False, "message": str}
    """
    surfer = _find_surfer()
    if not surfer:
        return {
            "success": False,
            "message": "Surfer not found. Install from https://surfer-project.org/ and add to PATH.",
        }

    if not vcd_path.is_file():
        return {"success": False, "message": f"VCD file not found: {vcd_path}"}

    try:
        # Generate state file with analog settings for multi-bit signals
        state_path = _generate_surfer_state(vcd_path)
        cmd = [str(surfer), str(vcd_path), "-s", str(state_path)]
        subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        logger.info("Launched Surfer: %s", " ".join(cmd))
        return {"success": True, "message": f"Opened {vcd_path.name} in Surfer"}
    except Exception as e:
        logger.error("Failed to launch Surfer: %s", e)
        return {"success": False, "message": f"Failed to launch Surfer: {e}"}


def _generate_surfer_state(vcd_path: Path) -> Path:
    """Generate a .surf.ron state file for a VCD file.

    1-bit signals: digital display (analog: None)
    Multi-bit signals: Signed format + analog Step/Viewport
    """
    parsed = parse_vcd(vcd_path)
    signals = parsed["signals"]

    # Build displayed_items entries
    items_list = []
    items_map = []
    for idx, sig in enumerate(signals, start=1):
        # items_tree entry
        items_list.append(f"""                (
                    item_ref: ({idx}),
                    level: 0,
                    unfolded: true,
                    selected: false,
                )""")

        # Determine analog/format settings
        if sig["size"] == 1:
            fmt = "None"
            analog = "None"
        else:
            fmt = 'Some("Signed")'
            analog = """Some((
                    settings: (
                        render_style: Step,
                        y_axis_scale: Viewport,
                    ),
                ))"""

        # Build scope path
        scope_parts = sig["scope"].split(".") if sig["scope"] else []
        scope_strs = ",\n".join(f'                            "{s}"' for s in scope_parts)

        items_map.append(f"""            ({idx}): Variable((
                variable_ref: (
                    path: (
                        strs: [
{scope_strs}
                        ],
                        id: r#None,
                    ),
                    name: "{sig['name']}",
                    id: Wellen(({idx})),
                    index: None,
                ),
                color: None,
                background_color: None,
                display_name: "{sig['name']}",
                display_name_type: Unique,
                manual_name: None,
                format: {fmt},
                field_formats: [],
                height_scaling_factor: None,
                analog: {analog},
            ))""")

    items_tree_str = ",\n".join(items_list)
    items_map_str = ",\n".join(items_map)
    vcd_path_str = str(vcd_path).replace("\\", "/")

    ron = f"""(
    show_hierarchy: None,
    show_menu: None,
    show_ticks: None,
    show_toolbar: None,
    show_tooltip: None,
    show_scope_tooltip: None,
    show_default_timeline: None,
    show_overview: None,
    show_statusbar: None,
    align_names_right: None,
    show_variable_indices: None,
    show_variable_direction: None,
    show_empty_scopes: None,
    show_hierarchy_icons: None,
    show_parameters_in_scopes: None,
    parameter_display_location: None,
    highlight_focused: None,
    fill_high_values: None,
    primary_button_drag_behavior: None,
    arrow_key_bindings: None,
    clock_highlight_type: None,
    hierarchy_style: None,
    autoload_sibling_state_files: None,
    autoreload_files: None,
    waves: Some((
        source: File("{vcd_path_str}"),
        format: Vcd,
        active_scope: None,
        items_tree: (
            items: [
{items_tree_str},
            ],
        ),
        displayed_items: {{
{items_map_str},
        }},
        display_item_ref_counter: {len(signals)},
        viewports: [
            (
                curr_left: (0.0),
                curr_right: (1.0),
                target_left: (0.0),
                target_right: (1.0),
                move_start_left: (0.0),
                move_start_right: (1.0),
                move_duration: None,
                move_strategy: Instant,
            ),
        ],
        cursor: None,
        markers: {{}},
        focused_item: None,
        focused_transaction: (None, None),
        default_variable_name_type: Unique,
        scroll_offset: 0.0,
        display_variable_indices: true,
        graphics: {{}},
    )),
    drag_started: false,
    drag_source_idx: None,
    drag_target_idx: None,
    previous_waves: None,
    count: None,
    blacklisted_translators: [],
    show_about: false,
    show_keys: false,
    show_gestures: false,
    show_quick_start: false,
    show_license: false,
    show_performance: false,
    show_logs: false,
    show_cursor_window: false,
    frame_buffer: (
        pixels_per_row: 16,
        square_pixels: true,
        rgb_mode: false,
        grayscale_bits: 1,
        r_bits: 3,
        g_bits: 3,
        b_bits: 2,
    ),
    wanted_timeunit: FemtoSeconds,
    time_string_format: None,
    show_url_entry: false,
    variable_name_filter_focused: false,
    variable_filter: (
        name_filter_type: Contain,
        name_filter_str: "",
        name_filter_case_insensitive: true,
        include_inputs: true,
        include_outputs: true,
        include_inouts: true,
        include_others: true,
        group_by_direction: false,
    ),
    sidepanel_width: Some(300.0),
    ui_zoom_factor: None,
    animation_enabled: None,
    use_dinotrace_style: None,
    transition_value: None,
)
"""
    # Write to temp file (persist — Surfer needs it while running)
    state_path = vcd_path.with_suffix(".surf.ron")
    state_path.write_text(ron, encoding="utf-8")
    logger.info("Generated Surfer state: %s", state_path)
    return state_path


def parse_vcd(path: Path) -> dict:
    """Parse a VCD file and return structured signal data.

    Returns:
        {
            "timescale": str,
            "signals": [{"id": str, "name": str, "size": int, "scope": str}],
            "changes": {signal_id: [(time_int, value_str), ...]},
        }
    """
    text = path.read_text(errors="replace")
    lines = text.splitlines()

    timescale = ""
    signals: list[dict] = []
    changes: dict[str, list[tuple[int, str]]] = {}
    scope_stack: list[str] = []

    i = 0
    # --- Header section ---
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("$timescale"):
            ts = _extract_field(lines, i, "$timescale")
            timescale = ts
            while i < len(lines) and "$end" not in lines[i]:
                i += 1
        elif line.startswith("$scope"):
            parts = line.split()
            if len(parts) >= 3:
                scope_stack.append(parts[2])
        elif line.startswith("$upscope"):
            if scope_stack:
                scope_stack.pop()
        elif line.startswith("$var"):
            parts = line.split()
            if len(parts) >= 5:
                sig = {
                    "id": parts[3],
                    "name": parts[4],
                    "size": int(parts[2]),
                    "scope": ".".join(scope_stack),
                }
                signals.append(sig)
                changes[sig["id"]] = []
        elif line.startswith("$enddefinitions"):
            i += 1
            break
        i += 1

    # --- Data section ---
    current_time = 0
    while i < len(lines):
        line = lines[i].strip()
        if not line or line.startswith("$"):
            i += 1
            continue
        if line.startswith("#"):
            current_time = int(line[1:])
        elif line.startswith("b") or line.startswith("B"):
            parts = line.split()
            if len(parts) == 2:
                val_str = parts[0][1:]
                sig_id = parts[1]
                if sig_id in changes:
                    changes[sig_id].append((current_time, val_str))
        elif len(line) >= 2 and line[0] in "01xzXZ":
            val = line[0]
            sig_id = line[1:]
            if sig_id in changes:
                changes[sig_id].append((current_time, val))
        i += 1

    return {"timescale": timescale, "signals": signals, "changes": changes}


def _extract_field(lines: list[str], start: int, keyword: str) -> str:
    """Extract text between $keyword and $end."""
    combined = ""
    for j in range(start, min(start + 5, len(lines))):
        combined += " " + lines[j]
    m = re.search(rf"\{keyword}\s+(.*?)\s*\$end", combined)
    return m.group(1).strip() if m else ""


def list_vcd_signals(vcd_path: Path) -> list[dict]:
    """List all signals in a VCD file.

    Returns: [{"name": str, "size": int, "scope": str}, ...]
    """
    parsed = parse_vcd(vcd_path)
    return [{"name": s["name"], "size": s["size"], "scope": s["scope"]}
            for s in parsed["signals"]]
